### ISSUE TITLE
Host on Github Pages

### ISSUE THREAD

**Issue by arirawr** [Zulban/coding-playground-website#1]
This is a completely static site - host it on GH-Pages!

Some lovely community members may then contribute to improving the styling ;)

**Comment by Zulban** [comment]
Indeed it is. You got a problem with bootstrap? ;)

Although, I'm looking to migrate away from McGill's free web hosting soon. When I do this site won't be static, but probably a Python flask web app like my www.stuartspence.ca website. I agree the site could use work :P

By the way, I think the links didn't work because I set my domain to mask the URL... I turned it off but not www.codingplayground.ca forwards to something ugly. Oh well.

**Comment by arirawr** [comment]
I am indeed - doing a lot more open source maintaining for work so I'm trying to clean up anything older than a couple of years!

I'm well! Living in Stockholm, working at @EmbarkStudios :)
